[package]
name = "dkim-milter"
version = "0.0.1"
edition = "2021"
rust-version = "1.65.0"
description = "Milter for DKIM signing and verification"
license = "GPL-3.0-or-later"
categories = ["email"]
keywords = ["dkim", "email", "milter"]
repository = "https://gitlab.com/glts/dkim-milter"
exclude = ["/.gitignore"]

[dependencies]
# TODO drop base64:
base64 = "0.20.0"
bstr = { version = "1.0.1", default-features = false, features = ["std"] }
byte-strings = "0.2.2"
bytes = "1"
domain = { version = "0.7.1", features = ["resolv"] }
futures = "0.3.24"
idna = "0.3.0"
indymilter = "0.2.0-alpha.1"
ipnet = "2.5.0"
once_cell = "1.14.0"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.22.0", features = ["fs", "macros", "net", "rt", "rt-multi-thread", "sync"] }
tracing = "0.1.37"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
viadkim = { version = "0.0.1", default-features = false }

[dev-dependencies]
indymilter-test = "0.0.2"
