[package]
name = "dkim-milter"
version = "0.0.3"
edition = "2021"
rust-version = "1.65.0"
description = "Milter for DKIM signing and verification"
license = "GPL-3.0-or-later"
categories = ["email"]
keywords = ["dkim", "email", "milter"]
repository = "https://gitlab.com/glts/dkim-milter"
exclude = ["/.gitignore"]

[dependencies]
bstr = { version = "1.4.0", default-features = false, features = ["std"] }
byte-strings = "0.2.2"
domain = { version = "0.8.0", features = ["resolv"] }
futures = "0.3.27"
idna = "0.3.0"  # do we still need this?
indymilter = "0.2.0"
ipnet = "2.7.2"
log = "0.4.17"
once_cell = "1.17.1"
regex = "1.7.3"
signal-hook = "0.3.15"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
syslog = "6.1.0"
tokio = { version = "1.26.0", features = ["fs", "macros", "net", "rt", "rt-multi-thread", "sync"] }
#tracing = "0.1.37"
#tracing-journald = "0.3.0"
#tracing-subscriber = "0.3.16"
viadkim = { path = "../viadkim" }
#viadkim = "0.0.3"

[dev-dependencies]
indymilter-test = "0.0.3"

[features]
sha1 = ["viadkim/sha1"]
