[package]
name = "dkim-milter"
version = "0.0.4"
edition = "2021"
rust-version = "1.65.0"
description = "Milter for DKIM signing and verification"
license = "GPL-3.0-or-later"
categories = ["email"]
keywords = ["dkim", "email", "milter"]
repository = "https://gitlab.com/glts/dkim-milter"
exclude = ["/.gitignore"]

[dependencies]
bstr = { version = "1.5.0", default-features = false, features = ["std"] }
byte-strings = "0.3.1"
domain = { version = "0.8.0", features = ["resolv"] }
futures = "0.3.28"
idna = "0.4.0"  # do we still need this?
indymilter = "0.2.0"
ipnet = "2.7.2"
log = "0.4.19"
once_cell = "1.18.0"
regex = "1.8.4"
signal-hook = "0.3.15"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
syslog = "6.1.0"
tokio = { version = "1.28.2", features = ["fs", "macros", "net", "rt", "rt-multi-thread", "sync"] }
viadkim = { path = "../viadkim" }
#viadkim = "0.0.4"

[dev-dependencies]
indymilter-test = "0.0.3"

[features]
sha1 = ["viadkim/sha1"]
